workflow:
   rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: never
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

variables:
  NVM_DIR: "/home/.nvm"
  NODE_VERSION: 21.7.3 

stages:
  - setup
  - build
  - test

prepare-job:
  stage: setup
  before_script:
    - apt-get -y -qq update
    - apt-get install -y coreutils
  script:  
    - mkdir -p $NVM_DIR
    - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
    - export NVM_DIR="/home/.nvm"
    - if [ -s "$NVM_DIR/nvm.sh" ]; then ."$NVM_DIR/nvm.sh"; fi
    - nvm ls-remote
    - nvm install $NODE_VERSION
    - nvm use $NODE_VERSION
    - nvm alias default $NODE_VERSION
    - node -v
    - npm -v   

build-job:
  stage: build
  script:
    - npm install
    - npm run build

test-job:
  stage: test
  script:
    - npm test    